### ISSUE TITLE
what is the FLOPs and parameters of your model?

### ISSUE THREAD

**Issue by JananiKugaa** [Little-Podi/AiATrack#1]

**Comment by Little-Podi** [comment]
The proposed AiATrack has **15.79M** model parameters and **9.43G** FLOPs model complexity according to the [THOP](https://github.com/Lyken17/pytorch-OpCounter) tool. If you want to verify it in this project, please refer to the open-source code of [STARK](https://github.com/researchmm/Stark) as a quick example.
