### ISSUE TITLE
HOW TIME

### ISSUE THREAD

**Issue by ChuangGe66** [Little-Podi/AiATrack#10]
一张24G的GPU需要训练多长时间

**Comment by Little-Podi** [comment]
Eight 2080 Ti GPUs (11GB) will take roughly 2 days, while 3090 GPUs (24GB) can halve the training cost.

**Comment by ChuangGe66** [comment]
I'm so excited you took the time to answer me

**Comment by Little-Podi** [comment]
You are welcome. Free to let me know if you have any other questions.

**Comment by ChuangGe66** [comment]
Thank you very much.
