### ISSUE TITLE
Training Logs

### ISSUE THREAD

**Issue by isbecky27** [Little-Podi/AiATrack#11]
Are there training logs for the models?

Thank you.

**Comment by Little-Podi** [comment]
The training logs are on the old server but I don't have the access to it right now. I'm not sure whether the project files have been removed or not. However, as the prediction head is identical to STARK, I suggest you have a look at [their training logs](https://github.com/researchmm/Stark/blob/main/MODEL_ZOO.md) as a reference. That is exactly what I did when developing this algorithm to make sure my training process is going well. Besides, if you meet any troubles, welcome to send the screenshots or the raw logs to me.

**Comment by isbecky27** [comment]
Actually, I wanted to check the IOU loss. STARK has a two-stage training process and the score head is only trained for 50 epochs. Therefore, I am curious about the loss variation during the training of the score head for 500 epochs.

**Comment by Little-Podi** [comment]
Oh, I see. Note that these two score heads are different both in implementation and supervision, so the loss of STARK score head can be totally different from AiATrack. Sorry, I forget the loss variation of the IoU prediction head thus I cannot give you a precise answer. Maybe someone else who reproduces this work can help.

**Comment by Little-Podi** [comment]
Besides, from my experience, compared with seperate two-stage training strategy, joint training the IoU prediction head and the target prediction head from the very beginning will achieve a much better precision in IoU prediction (the IoU prediction loss can reduce to a lower level without affecting other loss terms), thus yielding a better tracking performance.

**Comment by Little-Podi** [comment]
By the way, I don't know how will it work if we apply joint training strategy to STARK, but for AiATrack, that's the case.

**Comment by Little-Podi** [comment]
Hi, I just check the original paper of STARK and find that there's already a discussion about these two training strategies. In short, STARK cannot adopt a joint training strategy due to the distinct objectives of the two heads. In contrast, the design of IoU prediction head in AiATrack doesn't conflict with the target prediction head.

**Comment by Little-Podi** [comment]
Actually, showing by my own experimental results, maybe the learning of these two heads can complement each other. I conjecture that the proposed IoU prediction head in AiATrack could also serve as an alternative of the score head in STARK to further improve its training process and tracking performance.
