### ISSUE TITLE
Evaluate dataset

### ISSUE THREAD

**Issue by xuanquynh1307** [Little-Podi/AiATrack#13]
I have using evaluation server you provided, but in the trackingnet, I can't submit, and got10k didn't response me. And can you give me way to evaluate in VOT2020 dataset? Thank you

**Comment by Little-Podi** [comment]
Thanks for your asking. For TrackingNet and GOT-10k, the provided links are absolutely up-to-date with their official websites. I just tried the links and there were indeed some response errors. Maybe you can wait for one or two days. For VOT evaluation, it is not included in this project as that part was not well-organized so I cleaned it when I released the code. However, you can refer to [STARK+Alpha-Refine](https://github.com/researchmm/Stark/blob/main/external/AR/README.md) as a quick example. The results reported in my supplementary can be easily reproduced with the provided model checkpoint.
