### ISSUE TITLE
把encoder数量设为1，再换一个轻量级的backbone，这样会损失多少精度？有对应的消融实验吗？

### ISSUE THREAD

**Issue by Bigelephant0** [Little-Podi/AiATrack#14]

**Comment by Little-Podi** [comment]
I haven't performed such ablations. Welcome to have a try and share the results if you like.

**Comment by Bigelephant0** [comment]
在GOT10k数据集上，模型裁剪的小了，AO上升了。但是在其他数据集上不具备这个性质。

我把resnet换成了fbnet，encoder降为1层，transformer隐藏层维度改成了128。 GOT10k的AO达到了73.2。

**Comment by Little-Podi** [comment]
Glad to know that. By the way, may I ask if you only use the training subset of GOT-10k for its evaluation?

**Comment by Bigelephant0** [comment]
使用了TrackingNet、GOT10K、Lasot、coco这四个数据集，也就是你公开的代码里使用的四个数据集。

我想结合mae，尝试看看能不能把裁剪后的模型的指标提上去。目前即使没有mae预训练的模型，其指标也比feartrack高很多。在3060上可以有80FPS。

**Comment by Bigelephant0** [comment]
用两张2080ti训练的，batchsize是16*2

**Comment by Little-Podi** [comment]
I see. However, according to the protocol of GOT-10k, trackers evaluated on its testing subset should only be trained with its training subset. Thus, your comparison might be unfair.

**Comment by Little-Podi** [comment]
Please take a look at [this config file](https://github.com/Little-Podi/AiATrack/blob/main/experiments/aiatrack/baseline_got.yaml).

**Comment by Bigelephant0** [comment]
Okay, thank you.
