### ISSUE TITLE
Training Time?

### ISSUE THREAD

**Issue by JananiKugaa** [Little-Podi/AiATrack#2]
Could you provide your total training time ?

**Comment by Little-Podi** [comment]
Hi, I have included the training cost in [README](https://github.com/Little-Podi/AiATrack#bookmarktraining-cost). It takes nearly 2 days to train our model on eight 2080 Ti GPUs. I don't remember the exact training hours, but it's about 40 to 50 hours I think. Also, it depends a lot on your CPU and other processes running on the server.
