### ISSUE TITLE
congratulations！

### ISSUE THREAD

**Issue by HoungJee** [Little-Podi/AiATrack#21]
恭喜恭喜🎉
有一个问题想咨询一下，我在跑got10k和trackingnet的时候都很顺利，结果也进行了测试，但是在跑otb的时候fps显示都是-1，请问这个是异常还是怎么回事
谢谢啦😁

**Comment by Little-Podi** [comment]
你好呀～应该是你已经测过了OTB，然后对于已有结果的序列会跳过，FPS显示-1。

**Comment by HoungJee** [comment]
> 你好呀～应该是你已经测过了OTB，然后对于已有结果的序列会跳过，FPS显示-1。

嗷嗷 谢谢啦😁
