### ISSUE TITLE
multiple result file for UAV123 results

### ISSUE THREAD

**Issue by mribrahim** [Little-Podi/AiATrack#4]
Hi,

I have downloaded the raw results. I am interested in UAV123 dataset. I wonder the multiple file results as follows:

you have multiple files for some sequences such as:
 uav_bird1 (uav_bird1_1 + uav_bird1_2 + uav_bird1_3)
 uav_car1 (uav_car1_1 + uav_car1_2 + uav_car1_3 + uav_car1_s)
..
..

My questions are:

Should we combine them to a file?
Your tracker lost the target and have you restarted it again in these cases?

**Comment by Little-Podi** [comment]
Hi. For the 1st question, no, **you do not need to combine them to a file**. The split corresponds to the annotation structure of the UAV123 dataset. The official UAV123 dataset split some sequences into multiple subsequences for evaluation (each subsequence has different attributes and maybe has a different object to track). Please refer to [lib/test/evaluation/uavdataset.py](https://github.com/Little-Podi/AiATrack/blob/main/lib/test/evaluation/uavdataset.py) to find the specific startFrame and endFrame of each subsequence. For the 2nd question, **AiATrack does not restart tracking when the target is lost**. Note that no ground truth will be provided after the first frame in each sequence. In AiATrack, we just assume the target always exists, and we output a prediction for each frame around the target location that we predicted in the latest frame. It's an adaptive process. Fortunately, the target can be captured when it appears again after loss. You can try some manual strategies to facilitate the re-detection. For example, [increasing the search region](https://arxiv.org/abs/1808.06048) or [using global search](https://arxiv.org/abs/1909.01840) when the output score is relatively low.

**Comment by mribrahim** [comment]
Thanks for your detailed answer, and congratulations for such a beautiful work.
