### ISSUE TITLE
How to calculate FPS?

### ISSUE THREAD

**Issue by davitpapikyan** [Little-Podi/AiATrack#6]
Thank you all for this great work!
I wonder, do you have a script for evaluating FPS like [this](https://github.com/botaoye/OSTrack/blob/main/tracking/profile_model.py)?

**Comment by Little-Podi** [comment]
Hi Davit. The rough inference speed will be directly printed in your terminal. If you want to get a more precise evaluation as the script you mentioned, I would recommend you refer to [profile_model.py](https://github.com/researchmm/Stark/blob/main/tracking/profile_model.py) of STARK and modify the related forward code in [aiatrack.py](https://github.com/Little-Podi/AiATrack/blob/main/lib/models/aiatrack/aiatrack.py) accordingly. The results should be **15.79M** for model parameters and **9.43G** FLOPs for computation complexity.

**Comment by davitpapikyan** [comment]
Nice, thank you very much!

**Comment by Little-Podi** [comment]
I'm going to close this issue. Free to let me know if you need further help.
