### ISSUE TITLE
multigpu train

### ISSUE THREAD

**Issue by Hiyao-yy** [Little-Podi/AiATrack#7]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256]] is at version 7; expected version 6 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Are you experiencing this problem?

**Comment by Little-Podi** [comment]
Honestly, no. Have you modified the code?

**Comment by Little-Podi** [comment]
From your title, are you meaning that it only happens in the multi-GPU training process?

**Comment by Little-Podi** [comment]
BTW, I don't think this issue could be caused by multi-GPU training.

**Comment by Hiyao-yy** [comment]
I have solved it, thank you. I did change the code and added a parameter “broadcast_buffers=False” to the DDP and it works

**Comment by Hiyao-yy** [comment]
I have solved it, thank you. I did change the code and added a parameter “broadcast_buffers=False” to the DDP and it works

**Comment by Little-Podi** [comment]
Cool. Glad to hear.
